In [1]:
import torch
torch.cuda.is_available()

False

In [2]:
torch.backends.mps.is_available()

True

In [3]:
import torch

tensor0d = torch.tensor(1)                #1

print(tensor0d.shape)

tensor1d = torch.tensor([1, 2, 3])        #2

print(tensor1d.shape)

tensor2d = torch.tensor([[1, 2],
                         [3, 4]])         #3

print(tensor2d.shape)

tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])  #4

print(tensor3d.shape)

torch.Size([])
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])


In [4]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [8]:
floatvec = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
new = floatvec.to(torch.float32)
print(new.dtype)

torch.float32


In [15]:
tensor2d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [14]:
tensor3d = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
tensor3d.T

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [18]:
%timeit tensor2d @ tensor3d 

1.12 μs ± 1.29 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%timeit 33 + 33

3.62 ns ± 0.0118 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [25]:
tensor2dmps = tensor2d.to('mps')
tensor2dmps

tensor([[1, 2, 3],
        [4, 5, 6]], device='mps:0')

In [24]:
tensor3dmps = tensor3d.to('mps')
tensor3dmps

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='mps:0')

In [26]:
%timeit tensor2dmps @ tensor3dmps

1.52 μs ± 14.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
